
const ftp = require("basic-ftp")

async function finalize() {
    const client = new ftp.Client()
    client.ftp.verbose = true
    try {
        await client.access({
            host: "147.93.14.87",
            user: "u786839041.chaveirorafael",
            password: "1q2w3e4r@@@SK",
            secure: false
        })

        console.log("Current dir:", await client.pwd())

        // 1. Ensure public_html exists
        console.log("Ensuring public_html exists...")
        await client.ensureDir("public_html")

        // 2. CD into public_html
        await client.cd("public_html")
        console.log("Entered public_html. Uploading files...")

        // 3. Upload contents of 'out' (generated by npm run build)
        await client.uploadFromDir("out")
        console.log("Upload to public_html completed.")

        // 4. Cleanup the root (move up and delete files that shouldn't be there)
        await client.cd("/")
        const rootList = await client.list()
        const filesToCleanup = [
            "index.html", "sitemap.xml", "robots.txt", "manifest.webmanifest",
            ".htaccess", "logo.png", "hero-image.png", "icon.svg", "index.txt"
        ]
        const dirsToCleanup = ["servicos", "contato", "sobre", "images", "404", "_next"]

        console.log("Cleaning up root files...")
        for (const file of filesToCleanup) {
            if (rootList.find(f => f.name === file && !f.isDirectory)) {
                try { await client.remove(file); console.log(`Deleted root file: ${file}`); } catch (e) { }
            }
        }

        console.log("Cleaning up root directories...")
        for (const dir of dirsToCleanup) {
            if (rootList.find(d => d.name === dir && d.isDirectory)) {
                try { await client.removeDir(dir); console.log(`Deleted root dir: ${dir}`); } catch (e) { }
            }
        }

        console.log("Cleanup and deployment finished.")
    } catch (err) {
        console.error(err)
    } finally {
        client.close()
    }
}
finalize()
